name: Tests for Linear Equation Solver C#

on:
  push:
    branches:
      - C#_v0.5
  pull_request:
    branches:
      - C#_v0.5
  workflow_dispatch:  #Allows Manual Triggering

permissions:
  checks: write
  contents: read

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore "Linear Equation Solver(High Precision).sln"

    - name: Build
      run: dotnet build "Linear Equation Solver(High Precision).sln" --configuration Debug

    - name: Run tests
      run: dotnet test "./Test/Test.csproj" --logger:"trx;LogFileName=test_results.trx"
    
    - name: Install trx2junit
      run: dotnet tool install -g trx2junit

    - name: Convert .trx to JUnit
      run: trx2junit ./Test/TestResults/test_results.trx

    - name: Upload test results to GitHub UI
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: ./Test/TestResults/test_results.xml
        reporter: java-junit
        fail-on-error: true