name: Tests for Linear Equation Solver C++

on:
  push:
    branches:
      - develop_v1.0
  pull_request:
    branches:
      - develop_v1.0
  workflow_dispatch:  #Allows Manual Triggering

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild "Linear Equation Solver(High Precision)(C++).sln" /p:Configuration=Debug /p:Platform=x64

    - name: Run unit tests
      run: |
        .\x64\Debug\Test.exe --gtest_output=xml:test_results.xml